name: .NET Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: sha256:994cc3113ce004ae73df11f0dbc5088cbe6bb0da1691dd7e6f55474202a4f211

        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: cookbookTesting

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5435:5432

    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        ASPNETCORE_ENVIRONMENT: Integration

    - name: Restore dependencies
      run: dotnet restore APIContinousIntegration.slnf

    - name: Build
      run: dotnet build APIContinousIntegration.slnf --no-restore

    - name: Test
      run: dotnet test APIContinousIntegration.slnf --no-build --verbosity normal
